import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    `maven-publish`
}

group = "com.jaidensiu"
version = providers.gradleProperty("libraryVersion").getOrElse("0.1.0-SNAPSHOT")

val generatedVersionDir = layout.buildDirectory.dir("generated/version/kotlin")

val generateCatalogVersion by tasks.registering {
    description = "Generates CatalogVersion.kt, exposing CATALOG_VERSION from the libraryVersion Gradle property."
    group = "build"
    val outputDir = generatedVersionDir
    val versionValue = version.toString()
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("com/jaidensiu/orbit/catalog/CatalogVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.jaidensiu.orbit.catalog

            import kotlin.js.JsExport

            // Generated by :catalog's generateCatalogVersion task from the `libraryVersion` Gradle property. Do not edit.
            @JsExport
            public const val CATALOG_VERSION: String = "$versionValue"

            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    jvmToolchain(17)

    jvm()

    js {
        outputModuleName = "orbit-catalog"
        nodejs()
        binaries.library()
        generateTypeScriptDefinitions()
        useCommonJs()
    }

    androidTarget {
        publishLibraryVariants("release")
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    val xcframeworkName = "OrbitCatalog"
    val xcf = XCFramework(xcframeworkName)
    listOf(
        iosArm64(),
        iosSimulatorArm64(),
        iosX64(),
    ).forEach { target ->
        target.binaries.framework {
            baseName = xcframeworkName
            binaryOption("bundleId", "com.jaidensiu.orbit.catalog")
            isStatic = true
            xcf.add(this)
        }
    }

    sourceSets {
        all {
            languageSettings.optIn("kotlin.experimental.ExperimentalObjCName")
            languageSettings.optIn("kotlin.js.ExperimentalJsExport")
        }
        commonMain {
            kotlin.srcDir(generateCatalogVersion)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

android {
    namespace = "com.jaidensiu.orbit.catalog"
    compileSdk = 35

    defaultConfig {
        minSdk = 23
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/jaidensiu/orbit")
            credentials {
                username = providers.gradleProperty("gpr.user")
                    .orElse(providers.environmentVariable("GITHUB_ACTOR"))
                    .getOrElse("")
                password = providers.gradleProperty("gpr.token")
                    .orElse(providers.environmentVariable("GITHUB_TOKEN"))
                    .getOrElse("")
            }
        }
    }
}

afterEvaluate {
    (publishing.publications.getByName("kotlinMultiplatform") as MavenPublication).artifactId = "orbit-catalog"
}

val assembleNpmPackage by tasks.registering(Sync::class) {
    description = "Assembles the publishable npm package (scoped name, repository metadata) from the Kotlin/JS library distribution."
    group = "build"
    val versionValue = version.toString()
    from(tasks.named("jsNodeProductionLibraryDistribution"))
    into(layout.buildDirectory.dir("npmPackage"))
    doLast {
        val packageJson = destinationDir.resolve("package.json")
        @Suppress("UNCHECKED_CAST")
        val json = groovy.json.JsonSlurper().parse(packageJson) as MutableMap<String, Any>
        check(json["name"] == "orbit-catalog") { "unexpected generated package name '${json["name"]}'" }
        // GitHub Packages npm requires a scope matching the repository owner.
        json["name"] = "@jaidensiu/orbit-catalog"
        json["version"] = versionValue
        json["description"] = "Orbit analytics event catalog, generated from the Kotlin Multiplatform source of truth"
        json["license"] = "UNLICENSED"
        json["repository"] = mapOf("type" to "git", "url" to "git+https://github.com/jaidensiu/orbit.git")
        json["publishConfig"] = mapOf("registry" to "https://npm.pkg.github.com")
        packageJson.writeText(groovy.json.JsonOutput.prettyPrint(groovy.json.JsonOutput.toJson(json)) + "\n")
    }
}
